### ISSUE TITLE
Multiselect support

### ISSUE THREAD

**Issue by chy89310** [3lvis/Form#593]
Hi guys! Appreciate your great job to save my life! 

I've meet an issue to support multiple select in my project just like many other people using this plugin do.

And finally me and my college come up with a solution to extend the FORMSelectFieldCell to support multiple select to make things simple. Gif show how it work:
![aug-01-2018 11-51-33](https://user-images.githubusercontent.com/4516254/43500080-4f484ca2-9581-11e8-9e74-2e77cc55cba2.gif)

For more details, please take a look of my forked repo in **multselect** branch:
[https://github.com/kevinsumios/Form/tree/multiselect](https://github.com/kevinsumios/Form/tree/multiselect)

It would be great if our jobs help you guys to support the multiple select and it is welcome to at me whenever you need some contribution with this feature. Cheers.

**Comment by 3lvis** [comment]
Hi Kevin! I think this is a great MVP for multiselect. Would you mind making a PR with it?

**Comment by chy89310** [comment]
@3lvis I'd love to. I will checkout the latest commit and make a PR ASAP.

**Comment by chy89310** [comment]
@3lvis PR created! #594 
Please advice if any unit test is required. Thank you.

**Comment by richardtop** [comment]
I'm closing this issue as the implementation has been merged.

**Comment by 3lvis** [comment]
🔥
